package org.neocities.betalemon.socialwall

const val COLLECTION_MESSAGES = "messages"
const val COLLECTION_USERS = "users"
const val COLLECTION_NEWS = "news"
const val USER_AVATAR = "avatarUrl"
const val USER_ID = "userId"
const val USER_MAIL = "email"
const val USER_NAME = "username"
const val USER_PASSWORD = "username"
const val USER_PREFS = "userPreferences"
const val PREF_USERID = "pref_userID"
const val PREF_USERNAME = "pref_username"
const val MSG_USERNAME = "username"
const val MSG_TEXT = "text"
const val MSG_DATE = "createdAt"
const val NEWS_DATE = "createdAt"
const val NEWS_AUTHOR = "author"
const val NEWS_DESCRIPTION = "description"
const val NEWS_IMAGE = "imageUrl"
const val NEWS_TITLE = "title"
const val DB_AVATARS = "images/users"