package org.neocities.betalemon.socialwall

val COLLECTION_MESSAGES = "messages"
val COLLECTION_USERS = "users"
val COLLECTION_NEWS = "news"
val USER_AVATAR = "avatarUrl"
val USER_ID = "userId"
val USER_MAIL = "email"
val USER_NAME = "username"
val USER_PASSWORD = "username"
val USER_PREFS = "userPreferences"
val PREF_USERID = "pref_userID"
val PREF_USERNAME = "pref_username"
val MSG_USERNAME = "username"
val MSG_TEXT = "text"
val MSG_DATE = "createdAt"
val NEWS_DATE = "createdAt"
val NEWS_AUTHOR = "author"
val NEWS_DESCRIPTION = "description"
val NEWS_IMAGE = "imageUrl"
val NEWS_TITLE = "title"